<?php
namespace Loader\Utility\Node;

use essentials\addon\NodeEditor\CollectorNode;

class ArrayCollectorNode extends CollectorNode{

    public $in = [
        'value' => 'mixed'
    ];

    public $out = [
        'array' => 'Array',
    ];

    protected $array = [];

    public function reset()
    {
        parent::reset(); // TODO: Change the autogenerated stub
        $this->array = [];
    }

    public function method(array $inputs) {
        $this->array[] = $inputs['value'];
        return ['array' => $this->array];
    }
}